build:
  briks:
    image: openjdk:8-jdk
    commands:
      - ./gradlew build


notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: hack-devops
    from: drone
    when:
      branch: master
      event: push
      failure: true
  pull-request:
    image: slack
    webhook_url: https://hooks.slack.com/services/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
    channel: hack-devops
    from: drone
    template: ":thefalcon: *Ready for review* - {{build.title}}\n - {{build.link_url}}\n - by {{build.author}}"
    when:
      success: true
      event: pull_request
